/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bib;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;

/**
 *
 * @author Mariano Rack
 */
public class adminscreen extends javax.swing.JFrame {

    /**
     * Creates new form adminscreen
     */
    public adminscreen() {
        initComponents();
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        bteliminar = new java.awt.Button();
        btcrear = new java.awt.Button();
        btmostrar = new java.awt.Button();
        btmodificar = new java.awt.Button();
        btmodificarbib = new java.awt.Button();
        bteliminarbib = new java.awt.Button();
        btmostrarbib = new java.awt.Button();
        btcrearbib = new java.awt.Button();
        label3 = new java.awt.Label();
        btback = new java.awt.Button();
        btreporteusuarios = new javax.swing.JButton();
        btlibros = new javax.swing.JButton();
        btexistencia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        label2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        label2.setText("Usuarios");

        bteliminar.setBackground(new java.awt.Color(255, 102, 0));
        bteliminar.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        bteliminar.setForeground(new java.awt.Color(255, 255, 255));
        bteliminar.setLabel("Eliminar");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        btcrear.setBackground(new java.awt.Color(0, 102, 51));
        btcrear.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btcrear.setForeground(new java.awt.Color(255, 255, 255));
        btcrear.setLabel("Crear");
        btcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcrearActionPerformed(evt);
            }
        });

        btmostrar.setBackground(new java.awt.Color(0, 102, 51));
        btmostrar.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btmostrar.setForeground(new java.awt.Color(255, 255, 255));
        btmostrar.setLabel("Mostrar");
        btmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmostrarActionPerformed(evt);
            }
        });

        btmodificar.setBackground(new java.awt.Color(0, 102, 51));
        btmodificar.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btmodificar.setLabel("Modificar");
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });

        btmodificarbib.setBackground(new java.awt.Color(0, 102, 51));
        btmodificarbib.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btmodificarbib.setForeground(new java.awt.Color(255, 255, 255));
        btmodificarbib.setLabel("Modificar");
        btmodificarbib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarbibActionPerformed(evt);
            }
        });

        bteliminarbib.setBackground(new java.awt.Color(255, 102, 0));
        bteliminarbib.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        bteliminarbib.setForeground(new java.awt.Color(255, 255, 255));
        bteliminarbib.setLabel("Eliminar");
        bteliminarbib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarbibActionPerformed(evt);
            }
        });

        btmostrarbib.setBackground(new java.awt.Color(0, 102, 51));
        btmostrarbib.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btmostrarbib.setForeground(new java.awt.Color(255, 255, 255));
        btmostrarbib.setLabel("Mostrar");
        btmostrarbib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmostrarbibActionPerformed(evt);
            }
        });

        btcrearbib.setBackground(new java.awt.Color(0, 102, 51));
        btcrearbib.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btcrearbib.setForeground(new java.awt.Color(255, 255, 255));
        btcrearbib.setLabel("Crear");
        btcrearbib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcrearbibActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        label3.setText("Bibliografías");

        btback.setBackground(new java.awt.Color(0, 102, 51));
        btback.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btback.setForeground(new java.awt.Color(255, 255, 255));
        btback.setLabel("Regresar");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        btreporteusuarios.setBackground(new java.awt.Color(0, 102, 51));
        btreporteusuarios.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btreporteusuarios.setText("Reportar");
        btreporteusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreporteusuariosActionPerformed(evt);
            }
        });

        btlibros.setBackground(new java.awt.Color(0, 102, 51));
        btlibros.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btlibros.setText("Reportar libros");
        btlibros.setActionCommand("Reportar libros");
        btlibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlibrosActionPerformed(evt);
            }
        });

        btexistencia.setBackground(new java.awt.Color(0, 102, 51));
        btexistencia.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btexistencia.setText("Existencia");
        btexistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexistenciaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jButton1.setText("Rep Usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btback, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btreporteusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btlibros, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btexistencia)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btcrearbib, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmodificarbib, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bteliminarbib, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmostrarbib, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btcrear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bteliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btmostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btmodificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btcrear, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bteliminarbib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmostrarbib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmodificarbib, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btcrearbib, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btlibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btexistencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btreporteusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
this.setVisible(false);
new Eliminar().setVisible(true);
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcrearActionPerformed
        this.setVisible(false);
        new crearuser().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btcrearActionPerformed

    private void btmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmostrarActionPerformed
this.setVisible(false);
new Mostrar().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btmostrarActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
this.setVisible(false) ;
new Modificar().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btmodificarActionPerformed

    private void btmodificarbibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarbibActionPerformed
      this.setVisible(false);
        new ModifBiblios().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btmodificarbibActionPerformed

    private void bteliminarbibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarbibActionPerformed
this.setVisible(false);
        new EliminarBiblio().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bteliminarbibActionPerformed

    private void btmostrarbibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmostrarbibActionPerformed
new MostrarBiblios().setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btmostrarbibActionPerformed

    private void btcrearbibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcrearbibActionPerformed
new CrearBib().setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btcrearbibActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
 new log().setVisible(true);
                this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btbackActionPerformed

    private void btreporteusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreporteusuariosActionPerformed
String cadenaHTML = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte</title>\n"
                + "</head>\n"
                + "<body bgcolor=\"#A9D0F5\">\n"
        +"<p><font face=\"Kristen ITC\"><H1 align=\"center\" style=\"color:#04B404;font-size: 40px;\"> Reporte por Usuarios </H1></p>\n"
                + "<table border = \"2\" CELLPADDING = 15 align = \"center\">\n"
                + "        <tr>"
                + "          <th>Usuario</th>\n"
                + "          <th>Titulo</th>\n"
         + "          <th>Autor</th>\n"
         + "          <th>Tipo</th>\n"
                + "        </tr>";

        for (int i = 0; i < UserNormal.getLb().length; i++) {
            if (UserNormal.getLb()[i] != null) {
                cadenaHTML += "<tr>";
                cadenaHTML += "  <td>" + UserNormal.getLb()[i].getUser() + "</td>";
                cadenaHTML += "  <td>" + UserNormal.getLb()[i].getTitulo()+ "</td>";
                cadenaHTML += "  <td>" + UserNormal.getLb()[i].getAutor()+ "</td>";
                cadenaHTML += "  <td>" + UserNormal.getLb()[i].getTipo()+ "</td>";
                cadenaHTML += "</tr>";
            }
        }

        cadenaHTML += "      </table>\n"
                + "</body>\n"
                + "</html>";

        File archivo = new File("reporteus.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
            bw.write(cadenaHTML);
            bw.close();
        } catch (Exception e) {
        }        // TODO add your handling code here:
       
    }//GEN-LAST:event_btreporteusuariosActionPerformed

    private void btlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlibrosActionPerformed
String cadenaHTML = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte</title>\n"
                + "</head>\n"
                + "<body bgcolor=\"#A9D0F5\">\n"
        +"<p><font face=\"Kristen ITC\"><H1 align=\"center\" style=\"color:#04B404;font-size: 40px;\"> Libros Prestados </H1></p>\n"
                + "<table border = \"2\" CELLPADDING = 15 align = \"center\">\n"
                + "        <tr>"
                + "          <th>Titulo</th>\n"
         + "          <th>Autor</th>\n"
         + "          <th>Tipo</th>\n"
                + "        </tr>";

        for (int i = 0; i <= UserNormal.getLb().length-1; i++) {
            if (UserNormal.getLb()[i] != null) {
                cadenaHTML += "<tr>";
                cadenaHTML += "  <td>"  + UserNormal.getLb()[i].getTitulo()+ "</td>";
                cadenaHTML += "  <td>" + UserNormal.getLb()[i].getAutor()+ "</td>";
                cadenaHTML += "  <td>" + UserNormal.getLb()[i].getTipo()+ "</td>";
                cadenaHTML += "</tr>";
            }
        }

        cadenaHTML += "      </table>\n"
                + "</body>\n"
                + "</html>";

        File archivo = new File("reportelibrosprestados.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
            bw.write(cadenaHTML);
            bw.close();
        } catch (Exception e) {
        }          // TODO add your handling code here:
    }//GEN-LAST:event_btlibrosActionPerformed

    private void btexistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexistenciaActionPerformed
String cadenaHTML = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte</title>\n"
                + "</head>\n"
                + "<body bgcolor=\"#A9D0F5\">\n"
        +"<p><font face=\"Kristen ITC\"><H1 align=\"center\" style=\"color:#04B404;font-size: 40px;\"> Libros en Existencia </H1></p>\n"
                + "<table border = \"2\" CELLPADDING = 15 align = \"center\">\n"
                + "        <tr>"
                + "          <th>ID</th>\n"
                + "          <th>Título</th>\n"
         + "          <th>Autor</th>\n"
         + "          <th>Tipo</th>\n"
        + "          <th>Copias</th>\n"
                + "        </tr>";

        for (int i = 0; i <= Individual.getListabiblios().length-3; i++) {
            
                cadenaHTML += "<tr>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getIsbn()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getTitulo()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getAutor()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getTipo()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getCopias()+ "</td>";
                cadenaHTML += "</tr>";
            
        }

        cadenaHTML += "      </table>\n"
                + "</body>\n"
                + "</html>";

        File archivo = new File("LibrosExistencia.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
            bw.write(cadenaHTML);
            bw.close();
        } catch (Exception e) {
        }          // TODO add your handling code here:
    }//GEN-LAST:event_btexistenciaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String cadenaHTML = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte</title>\n"
                + "</head>\n"
                + "<body bgcolor=\"#A9D0F5\">\n"
        +"<p><font face=\"Kristen ITC\"><H1 align=\"center\" style=\"color:#04B404;font-size: 40px;\"> Usuarios </H1></p>\n"
                + "<table border = \"2\" CELLPADDING = 15 align = \"center\">\n"
                + "        <tr>"
                + "          <th>ID</th>\n"
                + "          <th>User</th>\n"
         + "          <th>Nombre</th>\n"
         + "          <th>Apellido</th>\n"
                + "        </tr>";

        for (int i = 0; i <= crearuser.getListausuarios().length-2; i++) {
            
                cadenaHTML += "<tr>";
                cadenaHTML += "  <td>" + crearuser.getListausuarios()[i].getId()+ "</td>";
                cadenaHTML += "  <td>" + crearuser.getListausuarios()[i].getUser()+ "</td>";
                cadenaHTML += "  <td>" + crearuser.getListausuarios()[i].getNombre()+ "</td>";
                cadenaHTML += "  <td>" + crearuser.getListausuarios()[i].getApellido()+ "</td>";
                cadenaHTML += "</tr>";
            
        }

        cadenaHTML += "      </table>\n"
                + "</body>\n"
                + "</html>";

        File archivo = new File("Usuarios.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
            bw.write(cadenaHTML);
            bw.close();
        } catch (Exception e) {
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btback;
    private java.awt.Button btcrear;
    private java.awt.Button btcrearbib;
    private java.awt.Button bteliminar;
    private java.awt.Button bteliminarbib;
    private javax.swing.JButton btexistencia;
    private javax.swing.JButton btlibros;
    private java.awt.Button btmodificar;
    private java.awt.Button btmodificarbib;
    private java.awt.Button btmostrar;
    private java.awt.Button btmostrarbib;
    private javax.swing.JButton btreporteusuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
