/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bib;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowFilter.Entry;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Mariano Rack
 */
public class BiblioVirtual extends javax.swing.JFrame {
Individual cr = new Individual();
 static Carrito[]listacarrito= new Carrito[2];
int n;
int x;

    /**
     * Creates new form BiblioVirtual
     */
    public BiblioVirtual() {
        initComponents();
        String[][] matriz = new String[cr.getListabiblios().length][14];
        for (int  i = 0; i < cr.getListabiblios().length; i++) {
             n=n+1;
            if (cr.getListabiblios()[i] != null) {
                if(cr.getListabiblios()[i].getTipo()=="Libro digital"){
       matriz[i][0]=""+n;
        matriz[i][1]=""+cr.getListabiblios()[i].getAutor();
        matriz[i][2]=cr.getListabiblios()[i].getAño();
        matriz[i][3]=cr.getListabiblios()[i].getTitulo();
        matriz[i][4]=cr.getListabiblios()[i].getDescripcion();
        matriz[i][5]=cr.getListabiblios()[i].getPalabras();
        matriz[i][6]=cr.getListabiblios()[i].getEdicion();
        matriz[i][7]=cr.getListabiblios()[i].getTemas();
        matriz[i][8]=""+cr.getListabiblios()[i].getCopias();
        matriz[i][9]=cr.getListabiblios()[i].getArea();
        matriz[i][10]=cr.getListabiblios()[i].getCategoria();
        matriz[i][11]=""+cr.getListabiblios()[i].getIsbn();
        matriz[i][12]=cr.getListabiblios()[i].getTipo();
        matriz[i][13]=cr.getListabiblios()[i].getIsbnreal();
                }
            }
           x=i;
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN"};
        tbmo.setModel(new DefaultTableModel(
                matriz,
                encabezado
        )); 
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btsearch = new java.awt.Button();
        btregresar1 = new java.awt.Button();
        btfiltrar = new javax.swing.JTextField();
        cbfiltrar = new javax.swing.JComboBox<>();
        btlogout2 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmo = new javax.swing.JTable();
        btverbib1 = new java.awt.Button();
        txtus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bib/logousac1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bib/us.png"))); // NOI18N

        btsearch.setActionCommand("Cargar");
        btsearch.setBackground(new java.awt.Color(0, 102, 51));
        btsearch.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btsearch.setForeground(new java.awt.Color(255, 255, 255));
        btsearch.setLabel("Buscar");
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });

        btregresar1.setActionCommand("Cargar");
        btregresar1.setBackground(new java.awt.Color(0, 102, 51));
        btregresar1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btregresar1.setForeground(new java.awt.Color(255, 255, 255));
        btregresar1.setLabel("Regresar");
        btregresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregresar1ActionPerformed(evt);
            }
        });

        btfiltrar.setText("🔍️");

        cbfiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autor", "Año", "Título", "Descripción", "Palabras", "Temas" }));

        btlogout2.setActionCommand("Cargar");
        btlogout2.setBackground(new java.awt.Color(0, 102, 51));
        btlogout2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btlogout2.setForeground(new java.awt.Color(255, 255, 255));
        btlogout2.setLabel("Logout");
        btlogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogout2ActionPerformed(evt);
            }
        });

        tbmo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Autor", "Año", "Titulo", "Descripción", "Palabras", "Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbmo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmo);

        btverbib1.setActionCommand("Cargar");
        btverbib1.setBackground(new java.awt.Color(0, 102, 51));
        btverbib1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btverbib1.setForeground(new java.awt.Color(255, 255, 255));
        btverbib1.setLabel("Ver Biblioteca Virtual");
        btverbib1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btverbib1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btregresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbfiltrar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btverbib1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(463, Short.MAX_VALUE)
                    .addComponent(btlogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btregresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btverbib1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(cbfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(btlogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(403, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
     // TODO add your handling code here:
      DefaultTableModel model = (DefaultTableModel) tbmo.getModel();
        final TableRowSorter< DefaultTableModel> sorter = new TableRowSorter< DefaultTableModel>(model);
        RowFilter<Object,Object> filtro = new RowFilter<Object,Object>() {
            public boolean include(Entry<? extends Object, ? extends Object> entry) {
              for (int i = entry.getValueCount() - 1; i >= 0; i--) {
                if (entry.getStringValue(i).contains(btfiltrar.getText())) {
                  return true;
                }
              }
                return false;
              }
            };
        tbmo.setRowSorter(sorter);
        int seleccion = cbfiltrar.getSelectedIndex();
        
        try {
            sorter.setRowFilter(filtro);
        } catch (PatternSyntaxException pse) {
            System.out.println("Bad regex pattern");
        }
    }//GEN-LAST:event_btsearchActionPerformed
private LbPrestados[] redimensionar1(LbPrestados[] arreglo) {
    LbPrestados[]temporal1=new LbPrestados[arreglo.length+1];
    for(int i=0; i<arreglo.length;i++){
        temporal1[i]=arreglo[i];
    }
        return temporal1;
}
    private Boolean hayespacio1(LbPrestados[] arreglo){
        Boolean espacio =false;
        for(int i=0;i<=arreglo.length;i++){
            if(arreglo[i]==null){
                espacio=true;
                break;
            }
        }
        return espacio;
    }
    private void btregresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregresar1ActionPerformed
this.setVisible(false);
        new UserNormal("").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btregresar1ActionPerformed

    private void btlogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogout2ActionPerformed
  if (!hayespacio1(UserNormal.lb)) {
            UserNormal.lb= redimensionar1(UserNormal.getLb());
        }
            for(int i=0;i<=UserNormal.getLb().length;i++){
                
if (UserNormal.getLb()[i] == null){

                    UserNormal.lb=redimensionar1(UserNormal.getLb());
                    
                    
for(int k=0;k<=BiblioVirtual.getListcarrito().length;k++){
    if (BiblioVirtual.getListcarrito()[i] != null) {
}
                    UserNormal.lb[i]= new LbPrestados(txtus.getText(),BiblioVirtual.getListcarrito()[k].getTitulo(),BiblioVirtual.getListcarrito()[k].getAutor(),BiblioVirtual.getListcarrito()[k].getTipo());
                
    for(int y=1;y<=UserNormal.lb.length;y++)
        {
            if (UserNormal.getLb()[y] != null) {
                System.out.println("----------------");
            System.out.println(UserNormal.lb[y].getUser());
            System.out.println(UserNormal.lb[y].getTitulo());
            System.out.println(UserNormal.lb[y].getAutor());
            System.out.println(UserNormal.lb[y].getTipo());
             System.out.println("----------------");
            break; 
            }
        }
                break;
              
}
            }
if (UserNormal.getLb()[i] != null){

                    UserNormal.lb=redimensionar1(UserNormal.getLb());
                    String concat="";
                    
for(int k=0;k<=BiblioVirtual.getListcarrito().length;k++){
    if (BiblioVirtual.getListcarrito()[i] != null) {
}
                    UserNormal.lb[i]= new LbPrestados(txtus.getText(),BiblioVirtual.getListcarrito()[k].getTitulo(),BiblioVirtual.getListcarrito()[k].getAutor(),BiblioVirtual.getListcarrito()[k].getTipo());
                
    for(int y=0;y<=UserNormal.lb.length;y++)
        {
            if (UserNormal.getLb()[y] != null) {
                System.out.println("----------------");
            System.out.println(UserNormal.lb[y].getUser());
            System.out.println(UserNormal.lb[y].getTitulo());
            System.out.println(UserNormal.lb[y].getAutor());
            System.out.println(UserNormal.lb[y].getTipo());
             System.out.println("----------------");
            break; 
            }
        }
                break;
              
}
            }
break; 
            }
        for(int i=0;i<BiblioVirtual.getListcarrito().length;i++){
        BiblioVirtual.getListcarrito()[i] = null;
    }
            
         new log().setVisible(true);
this.setVisible(false);     
    }//GEN-LAST:event_btlogout2ActionPerformed
private Carrito[] redimensionar1(Carrito[] arreglo) {
    Carrito[]temporal1=new Carrito[arreglo.length+1];
    for(int i=0; i<arreglo.length;i++){
        temporal1[i]=arreglo[i];
    }
        return temporal1;
}
    private Boolean hayespacio1(Carrito[] arreglo){
        Boolean espacio =false;
        for(int i=0;i<=arreglo.length;i++){
            if(arreglo[i]==null){
                espacio=true;
                break;
            }
        }
        return espacio;
    }
    public static Carrito[] getListcarrito() {
        return listacarrito;
    }
    private void tbmoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmoMouseClicked
 // primero, obtengo la fila seleccionada
String u=txtus.getText();
        int fila = this.tbmo.getSelectedRow();

if (!hayespacio1(listacarrito)) {
            setListacarrito(redimensionar1(getListcarrito()));
        }
            for(int i=0;i<=getListcarrito().length;i++){
                
if (getListcarrito()[i] == null){
                setListacarrito(redimensionar1(getListcarrito()));

                    listacarrito[i]= new Carrito(Individual.getListabiblios()[fila].getAutor(),Individual.getListabiblios()[fila].getAño(),cr.getListabiblios()[fila].getTitulo(),cr.getListabiblios()[fila].getDescripcion(),cr.getListabiblios()[fila].getPalabras(),cr.getListabiblios()[fila].getEdicion(),cr.getListabiblios()[fila].getTemas(),cr.getListabiblios()[fila].getCopias(),cr.getListabiblios()[fila].getArea(),cr.getListabiblios()[fila].getCategoria(),cr.getListabiblios()[fila].getIsbn(),cr.getListabiblios()[fila].getTipo(),cr.getListabiblios()[fila].getIsbnreal(),txtus.getText());
                System.out.println(getListcarrito()[i].getUser());
                System.out.println(txtus.getText());
    }
else if (getListcarrito()[i] != null){
                setListacarrito(redimensionar1(getListcarrito()));

                    listacarrito[i+1]= new Carrito(Individual.getListabiblios()[fila].getAutor(),Individual.getListabiblios()[fila].getAño(),cr.getListabiblios()[fila].getTitulo(),cr.getListabiblios()[fila].getDescripcion(),cr.getListabiblios()[fila].getPalabras(),cr.getListabiblios()[fila].getEdicion(),cr.getListabiblios()[fila].getTemas(),cr.getListabiblios()[fila].getCopias(),cr.getListabiblios()[fila].getArea(),cr.getListabiblios()[fila].getCategoria(),cr.getListabiblios()[fila].getIsbn(),cr.getListabiblios()[fila].getTipo(),cr.getListabiblios()[fila].getIsbnreal(),txtus.getText());
                System.out.println(getListcarrito()[i].getUser());
                System.out.println(txtus.getText());
    }
else {
        if(getListcarrito()[i].getIsbn()==Individual.getListabiblios()[fila].getIsbn()){
        listacarrito[i]= new Carrito(Individual.getListabiblios()[fila].getAutor(),cr.getListabiblios()[fila].getAño(),cr.getListabiblios()[fila].getTitulo(),cr.getListabiblios()[fila].getDescripcion(),cr.getListabiblios()[fila].getPalabras(),cr.getListabiblios()[fila].getEdicion(),cr.getListabiblios()[fila].getTemas(),cr.getListabiblios()[fila].getCopias(),cr.getListabiblios()[fila].getArea(),cr.getListabiblios()[fila].getCategoria(),cr.getListabiblios()[fila].getIsbn(),cr.getListabiblios()[fila].getTipo(),cr.getListabiblios()[fila].getIsbnreal(),txtus.getText());
   System.out.println(getListcarrito()[i].getUser());
   System.out.println(txtus.getText());
        }
    }
                    

                break;

            

            }
 
    }//GEN-LAST:event_tbmoMouseClicked

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
       String[][] matriz = new String[cr.getListabiblios().length][14];
        for (int  i = 0; i < cr.getListabiblios().length; i++) {
             n=n+1;
            if (cr.getListabiblios()[i] != null) {
       matriz[i][0]=""+n;
        matriz[i][1]=""+cr.getListabiblios()[i].getAutor();
        matriz[i][2]=cr.getListabiblios()[i].getAño();
        matriz[i][3]=cr.getListabiblios()[i].getTitulo();
        matriz[i][4]=cr.getListabiblios()[i].getDescripcion();
        matriz[i][5]=cr.getListabiblios()[i].getPalabras();
        matriz[i][6]=cr.getListabiblios()[i].getEdicion();
        matriz[i][7]=cr.getListabiblios()[i].getTemas();
        matriz[i][8]=""+cr.getListabiblios()[i].getCopias();
        matriz[i][9]=cr.getListabiblios()[i].getArea();
        matriz[i][10]=cr.getListabiblios()[i].getCategoria();
        matriz[i][11]=""+cr.getListabiblios()[i].getIsbn();
        matriz[i][12]=cr.getListabiblios()[i].getTipo();
        matriz[i][13]=cr.getListabiblios()[i].getIsbnreal();
            }
           x=i;
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN"};
        tbmo.setModel(new DefaultTableModel(
                matriz,
                encabezado
        ));  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    private void btverbib1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btverbib1ActionPerformed
this.setVisible(false);
        new Ver().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btverbib1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiblioVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiblioVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiblioVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiblioVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiblioVirtual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btfiltrar;
    private java.awt.Button btlogout2;
    private java.awt.Button btregresar1;
    private java.awt.Button btsearch;
    private java.awt.Button btverbib1;
    private javax.swing.JComboBox<String> cbfiltrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbmo;
    public static javax.swing.JTextField txtus;
    // End of variables declaration//GEN-END:variables

    /**
     * @param aListacarrito the listacarrito to set
     */
    public static void setListacarrito(Carrito[] aListacarrito) {
        listacarrito = aListacarrito;
    }
}
