/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bib;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Mariano Rack
 */
public class ConfirmarPresta extends javax.swing.JFrame {
int n,dispo;
    /**
     * Creates new form ConfirmarPresta
     */
    public ConfirmarPresta() {
        initComponents();
         String[][] matriz = new String[BiblioVirtual.getListcarrito().length][15];
        for (int i = 0; i < BiblioVirtual.getListcarrito().length; i++) {
             n=n+1;

            if (BiblioVirtual.getListcarrito()[i] != null) {
                matriz[i][0]=""+n;
                 matriz[i][1]=""+BiblioVirtual.getListcarrito()[i].getAutor();
        matriz[i][2]=BiblioVirtual.getListcarrito()[i].getAño();
        matriz[i][3]=BiblioVirtual.getListcarrito()[i].getTitulo();
        matriz[i][4]=BiblioVirtual.getListcarrito()[i].getDescripcion();
        matriz[i][5]=BiblioVirtual.getListcarrito()[i].getPalabras();
        matriz[i][6]=BiblioVirtual.getListcarrito()[i].getEdicion();
        matriz[i][7]=BiblioVirtual.getListcarrito()[i].getTemas();
        matriz[i][8]=""+(BiblioVirtual.getListcarrito()[i].getCopias());
        matriz[i][9]=BiblioVirtual.getListcarrito()[i].getArea();
        matriz[i][10]=BiblioVirtual.getListcarrito()[i].getCategoria();
        matriz[i][11]=""+BiblioVirtual.getListcarrito()[i].getIsbn();
        matriz[i][12]=BiblioVirtual.getListcarrito()[i].getTipo();
        matriz[i][13]=BiblioVirtual.getListcarrito()[i].getIsbnreal();
              matriz[i][14]=""+(BiblioVirtual.getListcarrito()[i].getCopias());  
              
                  
              
              for(int j=0; j<=Individual.getListabiblios().length;j++ ){
                  if(Individual.getListabiblios()[j] != null){
              if(Individual.getListabiblios()[j].getIsbn()==BiblioVirtual.getListcarrito()[i].getIsbn())    {
                   String ej=""+BiblioVirtual.getListcarrito()[i].getCopias();
    Individual.listabiblios[i]= new Biblios(BiblioVirtual.getListcarrito()[i].getAutor(),BiblioVirtual.getListcarrito()[i].getAño(),BiblioVirtual.getListcarrito()[i].getTitulo(),BiblioVirtual.getListcarrito()[i].getDescripcion(),BiblioVirtual.getListcarrito()[i].getPalabras(),BiblioVirtual.getListcarrito()[i].getEdicion(),BiblioVirtual.getListcarrito()[i].getTemas(),BiblioVirtual.getListcarrito()[i].getCopias()-1,BiblioVirtual.getListcarrito()[i].getArea(),BiblioVirtual.getListcarrito()[i].getCategoria(),BiblioVirtual.getListcarrito()[i].getIsbn(),BiblioVirtual.getListcarrito()[i].getTipo(),BiblioVirtual.getListcarrito()[i].getIsbnreal(),ej);
              }
    break;
            
              }
              }
              if(BiblioVirtual.getListcarrito()[i].getCopias()-1<0){
                  JOptionPane.showMessageDialog(null, "Ya no se encuentran unidades disponibles del libro: "+BiblioVirtual.getListcarrito()[i].getTitulo());
              }
            }
           
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN","Disponibles"};
        tb.setModel(new DefaultTableModel(
                matriz,
                encabezado
        )); 
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btbiblio2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb);

        btbiblio2.setActionCommand("Cargar");
        btbiblio2.setBackground(new java.awt.Color(0, 102, 51));
        btbiblio2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btbiblio2.setForeground(new java.awt.Color(255, 255, 255));
        btbiblio2.setLabel("Regresar");
        btbiblio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbiblio2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btbiblio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btbiblio2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbiblio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbiblio2ActionPerformed
       this.setVisible(false);
        new BiblioVirtual().setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btbiblio2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarPresta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btbiblio2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
