/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bib;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mariano Rack
 */
public class Libros extends javax.swing.JFrame {
int n,x;
Individual cr = new Individual();
    /**
     * Creates new form Libros
     */
    public Libros() {
        initComponents();
String[][] matriz = new String[cr.getListabiblios().length][14];
        for (int  i = 0; i < cr.getListabiblios().length; i++) {
             n=n+1;
            if (cr.getListabiblios()[i] != null) {
                if(cr.getListabiblios()[i].getTipo()!="Libro digital"){
       matriz[i][0]=""+n;
        matriz[i][1]=""+cr.getListabiblios()[i].getAutor();
        matriz[i][2]=cr.getListabiblios()[i].getAño();
        matriz[i][3]=cr.getListabiblios()[i].getTitulo();
        matriz[i][4]=cr.getListabiblios()[i].getDescripcion();
        matriz[i][5]=cr.getListabiblios()[i].getPalabras();
        matriz[i][6]=cr.getListabiblios()[i].getEdicion();
        matriz[i][7]=cr.getListabiblios()[i].getTemas();
        matriz[i][8]=""+cr.getListabiblios()[i].getCopias();
        matriz[i][9]=cr.getListabiblios()[i].getArea();
        matriz[i][10]=cr.getListabiblios()[i].getCategoria();
        matriz[i][11]=""+cr.getListabiblios()[i].getIsbn();
        matriz[i][12]=cr.getListabiblios()[i].getTipo();
        matriz[i][13]=cr.getListabiblios()[i].getIsbnreal();
                }
            }
           x=i;
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN"};
        tbmo.setModel(new DefaultTableModel(
                matriz,
                encabezado
        )); 
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btverpresta = new java.awt.Button();
        btsearch = new java.awt.Button();
        btregresar1 = new java.awt.Button();
        btfiltrar = new javax.swing.JTextField();
        cbfiltrar = new javax.swing.JComboBox<>();
        btlogout2 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmo = new javax.swing.JTable();
        f = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btrep = new javax.swing.JButton();
        txtus2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bib/logousac1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bib/us.png"))); // NOI18N

        btverpresta.setActionCommand("Cargar");
        btverpresta.setBackground(new java.awt.Color(0, 102, 51));
        btverpresta.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btverpresta.setForeground(new java.awt.Color(255, 255, 255));
        btverpresta.setLabel("Ver Préstamos");
        btverpresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btverprestaActionPerformed(evt);
            }
        });

        btsearch.setActionCommand("Cargar");
        btsearch.setBackground(new java.awt.Color(0, 102, 51));
        btsearch.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btsearch.setForeground(new java.awt.Color(255, 255, 255));
        btsearch.setLabel("Buscar");
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });

        btregresar1.setActionCommand("Cargar");
        btregresar1.setBackground(new java.awt.Color(0, 102, 51));
        btregresar1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btregresar1.setForeground(new java.awt.Color(255, 255, 255));
        btregresar1.setLabel("Regresar");
        btregresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregresar1ActionPerformed(evt);
            }
        });

        btfiltrar.setText("🔍️");

        cbfiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autor", "Año", "Título", "Descripción", "Palabras", "Temas" }));

        btlogout2.setActionCommand("Cargar");
        btlogout2.setBackground(new java.awt.Color(0, 102, 51));
        btlogout2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btlogout2.setForeground(new java.awt.Color(255, 255, 255));
        btlogout2.setLabel("Logout");
        btlogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogout2ActionPerformed(evt);
            }
        });

        tbmo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Autor", "Año", "Titulo", "Descripción", "Palabras", "Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbmo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmo);

        f.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Tesis", "Revista" }));

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btrep.setBackground(new java.awt.Color(0, 102, 51));
        btrep.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btrep.setText("REPORTE lIBROS");
        btrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btrep)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbfiltrar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btverpresta, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                                                .addComponent(btregresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(60, 60, 60))))))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(463, Short.MAX_VALUE)
                    .addComponent(btlogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btregresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btverpresta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbfiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btrep))
                        .addGap(1, 1, 1)
                        .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(btlogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(403, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Carrito[] redimensionar1(Carrito[] arreglo) {
    Carrito[]temporal1=new Carrito[arreglo.length+1];
    for(int i=0; i<arreglo.length;i++){
        temporal1[i]=arreglo[i];
    }
        return temporal1;
}
    private Boolean hayespacio1(Carrito[] arreglo){
        Boolean espacio =false;
        for(int i=0;i<=arreglo.length;i++){
            if(arreglo[i]==null){
                espacio=true;
                break;
            }
        }
        return espacio;
    }
    private void btverprestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btverprestaActionPerformed
        this.setVisible(false);
        new VerPrestamos().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btverprestaActionPerformed

    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
DefaultTableModel model = (DefaultTableModel) tbmo.getModel();
        final TableRowSorter< DefaultTableModel> sorter = new TableRowSorter< DefaultTableModel>(model);
        RowFilter<Object,Object> filtro = new RowFilter<Object,Object>() {
            public boolean include(Entry<? extends Object, ? extends Object> entry) {
              for (int i = entry.getValueCount() - 1; i >= 0; i--) {
                if (entry.getStringValue(i).contains(btfiltrar.getText())) {
                  return true;
                }
              }
                return false;
              }
            };
        tbmo.setRowSorter(sorter);
        int seleccion = cbfiltrar.getSelectedIndex();
        
        try {
            sorter.setRowFilter(filtro);
        } catch (PatternSyntaxException pse) {
            System.out.println("Bad regex pattern");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btsearchActionPerformed

    private void btregresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregresar1ActionPerformed
        this.setVisible(false);
        new UserNormal("").setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btregresar1ActionPerformed

    private void btlogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogout2ActionPerformed
        this.setVisible(false);
        new log().setVisible(true);
        for(int j=0;j<=BiblioVirtual.getListcarrito().length;j++){

        }
    }//GEN-LAST:event_btlogout2ActionPerformed

    private void tbmoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmoMouseClicked
        // primero, obtengo la fila seleccionada

        int fila = this.tbmo.getSelectedRow();

if (!hayespacio1(BiblioVirtual.listacarrito)) {
            BiblioVirtual.setListacarrito(redimensionar1(BiblioVirtual.getListcarrito()));
        }
            for(int i=0;i<=BiblioVirtual.getListcarrito().length;i++){
                
if (BiblioVirtual.getListcarrito()[i] == null){
    BiblioVirtual.setListacarrito(redimensionar1(BiblioVirtual.getListcarrito()));

                    BiblioVirtual.listacarrito[i]= new Carrito(Individual.getListabiblios()[fila].getAutor(),Individual.getListabiblios()[fila].getAño(),cr.getListabiblios()[fila].getTitulo(),cr.getListabiblios()[fila].getDescripcion(),cr.getListabiblios()[fila].getPalabras(),cr.getListabiblios()[fila].getEdicion(),cr.getListabiblios()[fila].getTemas(),cr.getListabiblios()[fila].getCopias(),cr.getListabiblios()[fila].getArea(),cr.getListabiblios()[fila].getCategoria(),cr.getListabiblios()[fila].getIsbn(),cr.getListabiblios()[fila].getTipo(),cr.getListabiblios()[fila].getIsbnreal(),txtus2.getText());
                System.out.println(""+BiblioVirtual.getListcarrito()[i].getAutor());
    }
else if (BiblioVirtual.getListcarrito()[i] != null){
    BiblioVirtual.setListacarrito(redimensionar1(BiblioVirtual.getListcarrito()));

                    BiblioVirtual.listacarrito[i+1]= new Carrito(Individual.getListabiblios()[fila].getAutor(),Individual.getListabiblios()[fila].getAño(),cr.getListabiblios()[fila].getTitulo(),cr.getListabiblios()[fila].getDescripcion(),cr.getListabiblios()[fila].getPalabras(),cr.getListabiblios()[fila].getEdicion(),cr.getListabiblios()[fila].getTemas(),cr.getListabiblios()[fila].getCopias(),cr.getListabiblios()[fila].getArea(),cr.getListabiblios()[fila].getCategoria(),cr.getListabiblios()[fila].getIsbn(),cr.getListabiblios()[fila].getTipo(),cr.getListabiblios()[fila].getIsbnreal(),txtus2.getText());
                
}
else {
        if(BiblioVirtual.getListcarrito()[i].getIsbn()==Individual.getListabiblios()[fila].getIsbn()){
        BiblioVirtual.listacarrito[i]= new Carrito(Individual.getListabiblios()[fila].getAutor(),cr.getListabiblios()[fila].getAño(),cr.getListabiblios()[fila].getTitulo(),cr.getListabiblios()[fila].getDescripcion(),cr.getListabiblios()[fila].getPalabras(),cr.getListabiblios()[fila].getEdicion(),cr.getListabiblios()[fila].getTemas(),cr.getListabiblios()[fila].getCopias(),cr.getListabiblios()[fila].getArea(),cr.getListabiblios()[fila].getCategoria(),cr.getListabiblios()[fila].getIsbn(),cr.getListabiblios()[fila].getTipo(),cr.getListabiblios()[fila].getIsbnreal(),txtus2.getText());
    }
    }
                    

                break;

            

            }

    }//GEN-LAST:event_tbmoMouseClicked

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
         String[][] matriz = new String[BiblioVirtual.getListcarrito().length][15];
        for (int i = 0; i < BiblioVirtual.getListcarrito().length; i++) {
             n=n+1;
            if (BiblioVirtual.getListcarrito()[i] != null) {
                if(BiblioVirtual.getListcarrito()[i].getTipo()!="Libro digital"){
                matriz[i][0]=""+n;
                 matriz[i][1]=""+BiblioVirtual.getListcarrito()[i].getAutor();
        matriz[i][2]=BiblioVirtual.getListcarrito()[i].getAño();
        matriz[i][3]=BiblioVirtual.getListcarrito()[i].getTitulo();
        matriz[i][4]=BiblioVirtual.getListcarrito()[i].getDescripcion();
        matriz[i][5]=BiblioVirtual.getListcarrito()[i].getPalabras();
        matriz[i][6]=BiblioVirtual.getListcarrito()[i].getEdicion();
        matriz[i][7]=BiblioVirtual.getListcarrito()[i].getTemas();
        matriz[i][8]=""+(BiblioVirtual.getListcarrito()[i].getCopias());
        matriz[i][9]=BiblioVirtual.getListcarrito()[i].getArea();
        matriz[i][10]=BiblioVirtual.getListcarrito()[i].getCategoria();
        matriz[i][11]=""+BiblioVirtual.getListcarrito()[i].getIsbn();
        matriz[i][12]=BiblioVirtual.getListcarrito()[i].getTipo();
        matriz[i][13]=BiblioVirtual.getListcarrito()[i].getIsbnreal();
              matriz[i][14]=""+(BiblioVirtual.getListcarrito()[i].getCopias());   
              for(int j=0; j<=Individual.getListabiblios().length;j++ ){
                  if(Individual.getListabiblios()[j] != null){
              if(Individual.getListabiblios()[j].getIsbn()==BiblioVirtual.getListcarrito()[i].getIsbn())    {
                   String ej=""+BiblioVirtual.getListcarrito()[i].getCopias();
    Individual.listabiblios[i]= new Biblios(BiblioVirtual.getListcarrito()[i].getAutor(),BiblioVirtual.getListcarrito()[i].getAño(),BiblioVirtual.getListcarrito()[i].getTitulo(),BiblioVirtual.getListcarrito()[i].getDescripcion(),BiblioVirtual.getListcarrito()[i].getPalabras(),BiblioVirtual.getListcarrito()[i].getEdicion(),BiblioVirtual.getListcarrito()[i].getTemas(),BiblioVirtual.getListcarrito()[i].getCopias()-1,BiblioVirtual.getListcarrito()[i].getArea(),BiblioVirtual.getListcarrito()[i].getCategoria(),BiblioVirtual.getListcarrito()[i].getIsbn(),BiblioVirtual.getListcarrito()[i].getTipo(),BiblioVirtual.getListcarrito()[i].getIsbnreal(),ej);
              }
    break;
            
              }
              }
              if(BiblioVirtual.getListcarrito()[i].getCopias()-1<0){
                  JOptionPane.showMessageDialog(null, "Ya no se encuentran unidades disponibles del libro: "+BiblioVirtual.getListcarrito()[i].getTitulo());
              }
            }
            }
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN","Disponibles"};
        tbmo.setModel(new DefaultTableModel(
                matriz,
                encabezado
        ));    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    private void btrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrepActionPerformed
       String cadenaHTML = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte</title>\n"
                + "</head>\n"
                + "<body bgcolor=\"#A9D0F5\">\n"
        +"<p><font face=\"Kristen ITC\"><H1 align=\"center\" style=\"color:#04B404;font-size: 40px;\"> Libros en Existencia </H1></p>\n"
                + "<table border = \"2\" CELLPADDING = 15 align = \"center\">\n"
                + "        <tr>"
                + "          <th>Identificador</th>\n"
                + "          <th>Título</th>\n"
         + "          <th>Autor</th>\n"
         + "          <th>Tipo</th>\n"
        + "          <th>Copias</th>\n"
                + "        </tr>";

        for (int i = 0; i <= Individual.getListabiblios().length-3; i++) {
            
                cadenaHTML += "<tr>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getIsbn()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getTitulo()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getAutor()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getTipo()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getCopias()+ "</td>";
                cadenaHTML += "</tr>";
            
        }

        cadenaHTML += "      </table>\n"
                + "</body>\n"
                + "</html>";

        File archivo = new File("LibrosExistenciaAñadir.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
            bw.write(cadenaHTML);
            bw.close();
        } catch (Exception e) {
        }                   // TODO add your handling code here:
    }//GEN-LAST:event_btrepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String tipo=f.getSelectedItem().toString();
        
       String[][] matriz = new String[cr.getListabiblios().length][14];
        for (int i = 0; i <= Individual.getListabiblios().length-3; i++) {
            
            if (tipo=="Libro") {
               if (cr.getListabiblios()[i] != null) {
                if (Individual.getListabiblios()[i].getTipo().equals("Libro")) {
                matriz[i][0]=""+n;
        matriz[i][1]=""+cr.getListabiblios()[i].getAutor();
        matriz[i][2]=cr.getListabiblios()[i].getAño();
        matriz[i][3]=cr.getListabiblios()[i].getTitulo();
        matriz[i][4]=cr.getListabiblios()[i].getDescripcion();
        matriz[i][5]=cr.getListabiblios()[i].getPalabras();
        matriz[i][6]=cr.getListabiblios()[i].getEdicion();
        matriz[i][7]=cr.getListabiblios()[i].getTemas();
        matriz[i][8]=""+cr.getListabiblios()[i].getCopias();
        matriz[i][9]=cr.getListabiblios()[i].getArea();
        matriz[i][10]=cr.getListabiblios()[i].getCategoria();
        matriz[i][11]=""+cr.getListabiblios()[i].getIsbn();
        matriz[i][12]=cr.getListabiblios()[i].getTipo();
        matriz[i][13]=cr.getListabiblios()[i].getIsbnreal();
               
                } 
            }
            }
            
            else if(tipo=="Revista"){
                if (cr.getListabiblios()[i] != null) {
                if ((Individual.getListabiblios()[i].getTipo().equals("Revista"))) {
              matriz[i][0]=""+n;
        matriz[i][1]=""+cr.getListabiblios()[i].getAutor();
        matriz[i][2]=cr.getListabiblios()[i].getAño();
        matriz[i][3]=cr.getListabiblios()[i].getTitulo();
        matriz[i][4]=cr.getListabiblios()[i].getDescripcion();
        matriz[i][5]=cr.getListabiblios()[i].getPalabras();
        matriz[i][6]=cr.getListabiblios()[i].getEdicion();
        matriz[i][7]=cr.getListabiblios()[i].getTemas();
        matriz[i][8]=""+cr.getListabiblios()[i].getCopias();
        matriz[i][9]=cr.getListabiblios()[i].getArea();
        matriz[i][10]=cr.getListabiblios()[i].getCategoria();
        matriz[i][11]=""+cr.getListabiblios()[i].getIsbn();
        matriz[i][12]=cr.getListabiblios()[i].getTipo();
        matriz[i][13]=cr.getListabiblios()[i].getIsbnreal();
                } 
            }
            }
            
            else if(tipo=="Tesis"){
                if (cr.getListabiblios()[i] != null) {
                if ((Individual.getListabiblios()[i].getTipo().equals("Tesis"))) {
               matriz[i][0]=""+n;
        matriz[i][1]=""+cr.getListabiblios()[i].getAutor();
        matriz[i][2]=cr.getListabiblios()[i].getAño();
        matriz[i][3]=cr.getListabiblios()[i].getTitulo();
        matriz[i][4]=cr.getListabiblios()[i].getDescripcion();
        matriz[i][5]=cr.getListabiblios()[i].getPalabras();
        matriz[i][6]=cr.getListabiblios()[i].getEdicion();
        matriz[i][7]=cr.getListabiblios()[i].getTemas();
        matriz[i][8]=""+cr.getListabiblios()[i].getCopias();
        matriz[i][9]=cr.getListabiblios()[i].getArea();
        matriz[i][10]=cr.getListabiblios()[i].getCategoria();
        matriz[i][11]=""+cr.getListabiblios()[i].getIsbn();
        matriz[i][12]=cr.getListabiblios()[i].getTipo();
        matriz[i][13]=cr.getListabiblios()[i].getIsbnreal();
                } 
            }
            }
            
            
            
        }
        
        String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN","Disponibles"};
        tbmo.setModel(new DefaultTableModel(matriz,encabezado));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btfiltrar;
    private java.awt.Button btlogout2;
    private java.awt.Button btregresar1;
    private javax.swing.JButton btrep;
    private java.awt.Button btsearch;
    private java.awt.Button btverpresta;
    private javax.swing.JComboBox<String> cbfiltrar;
    private javax.swing.JComboBox<String> f;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbmo;
    public static javax.swing.JTextField txtus2;
    // End of variables declaration//GEN-END:variables
}
