/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bib;
import javax.swing.JOptionPane;
/**
 *
 * @author Mariano Rack
 */
public class Masiva extends javax.swing.JFrame {
Individual cr = new Individual();
    /**
     * Creates new form Masiva
     */
    public Masiva() {
        initComponents();
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txbib = new javax.swing.JTextArea();
        btcancel = new java.awt.Button();
        btcargar1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        txbib.setColumns(20);
        txbib.setRows(5);
        jScrollPane1.setViewportView(txbib);

        btcancel.setActionCommand("Cargar");
        btcancel.setBackground(new java.awt.Color(0, 102, 51));
        btcancel.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btcancel.setForeground(new java.awt.Color(255, 255, 255));
        btcancel.setLabel("Cancelar");
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });

        btcargar1.setActionCommand("Cargar");
        btcargar1.setBackground(new java.awt.Color(0, 102, 51));
        btcargar1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btcargar1.setForeground(new java.awt.Color(255, 255, 255));
        btcargar1.setLabel("Cargar");
        btcargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcargar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(btcargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(452, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(360, Short.MAX_VALUE)
                    .addComponent(btcargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Biblios[] redimensionar1(Biblios[] arreglo) {
    Biblios[]temporal1=new Biblios[arreglo.length+1];
    for(int i=0; i<arreglo.length;i++){
        temporal1[i]=arreglo[i];
    }
        return temporal1;
}
    private Boolean hayespacio1(Biblios[] arreglo){
        Boolean espacio =false;
        for(int i=0;i<=arreglo.length;i++){
            if(arreglo[i]==null){
                espacio=true;
                break;
            }
        }
        return espacio;
    }
    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed

         new CrearBib().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_btcancelActionPerformed

    private void btcargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcargar1ActionPerformed

        String biblios= txbib.getText();
  String[] parts = biblios.split("\\R");  
  for(int j=0;j<parts.length;j++){
       
      String part1 = parts[j];
      String[] parts2 = part1.split(";");
      String tipo="";
     
      
       cr.getListabiblios();
      
       if (!hayespacio1(cr.listabiblios)) {
            cr.listabiblios= redimensionar1(cr.getListabiblios());
        }
        
            for(int i=0;i<=cr.getListabiblios().length;i++){
                
if (cr.getListabiblios()[i] == null){
String tipof="";
      if(null != parts2[11])switch (parts2[11]) {
        case "0":
            tipof="Libro";
            break;
        case "1":
            tipof="Revista";
            break;
        case "2":
            tipof="Tesis";
            break;
        default:
            break;
    }
                         int isbn = Integer.parseInt(parts2[10]);
                         int copias = Integer.parseInt(parts2[7]);
                   
                    cr.listabiblios=redimensionar1(cr.getListabiblios());
                    
                    Individual.listabiblios[i]= new Biblios(parts2[0],parts2[1],parts2[2],parts2[3],parts2[4],parts2[5],parts2[6],copias,parts2[8],parts2[9],isbn,tipof,parts2[12],parts2[13]);
                

                break;

            }
            }
  }
   JOptionPane.showMessageDialog(null, "Los libros se han creado con éxito");

                // TODO add your handling code here:
    }//GEN-LAST:event_btcargar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masiva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btcancel;
    private java.awt.Button btcargar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txbib;
    // End of variables declaration//GEN-END:variables
}
