/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bib;
import  static java.nio.file.Files.list;
import static java.util.Collections.list;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Mariano Rack
 */
public class Modificar extends javax.swing.JFrame {
crearuser cr = new crearuser();
Boolean existeusuario;
int x;
    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbid = new java.awt.Label();
        txtid = new javax.swing.JTextField();
        lbnom = new java.awt.Label();
        txtnom = new javax.swing.JTextField();
        lbape = new java.awt.Label();
        txtape = new javax.swing.JTextField();
        lbuser = new java.awt.Label();
        txtuser = new javax.swing.JTextField();
        lbrol = new java.awt.Label();
        txtrol = new javax.swing.JTextField();
        lbcontra = new java.awt.Label();
        lbcontracon = new java.awt.Label();
        btbuscar = new java.awt.Button();
        btcancelaruser = new java.awt.Button();
        btmodif1 = new java.awt.Button();
        txtpass = new javax.swing.JPasswordField();
        txtconfirmpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        lbid.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lbid.setText("ID");

        lbnom.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lbnom.setText("Nombre");

        lbape.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lbape.setText("Apellido");

        lbuser.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lbuser.setText("User");

        lbrol.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lbrol.setText("Rol");

        lbcontra.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lbcontra.setText("Contraseña");

        lbcontracon.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lbcontracon.setText("Confirmar Contraseña");

        btbuscar.setBackground(new java.awt.Color(0, 102, 51));
        btbuscar.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btbuscar.setLabel("Buscar");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        btcancelaruser.setBackground(new java.awt.Color(0, 102, 51));
        btcancelaruser.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btcancelaruser.setForeground(new java.awt.Color(255, 255, 255));
        btcancelaruser.setLabel("Cancelar");
        btcancelaruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelaruserActionPerformed(evt);
            }
        });

        btmodif1.setBackground(new java.awt.Color(0, 102, 51));
        btmodif1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btmodif1.setForeground(new java.awt.Color(255, 255, 255));
        btmodif1.setLabel("Modificar");
        btmodif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodif1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btmodif1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btcancelaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbrol, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtrol, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbuser, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbape, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbnom, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbid, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbcontracon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtconfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbcontracon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtconfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btcancelaruser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btmodif1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(443, 443, 443))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
existeusuario=false;
        String[][] matriz = new String[cr.getListausuarios().length][7];
        for (int i = 0; i < cr.getListausuarios().length; i++) {
            if (cr.getListausuarios()[i] != null) {
                existeusuario=true;
        matriz[i][1]=""+crearuser.getListausuarios()[i].getId();
        matriz[i][2]=crearuser.getListausuarios()[i].getNombre();
        matriz[i][3]=crearuser.getListausuarios()[i].getApellido();
        matriz[i][4]=crearuser.getListausuarios()[i].getUser();
        matriz[i][5]=crearuser.getListausuarios()[i].getRol();
        matriz[i][6]=crearuser.getListausuarios()[i].getPass();
            if(matriz[i][1].equals(txtid.getText()))    {
    txtnom.setText(matriz[i][2]);
     txtape.setText(matriz[i][3]);
      txtuser.setText(matriz[i][4]);
       txtrol.setText(matriz[i][5]);
        txtpass.setText(matriz[i][6]);
       for(int y=0;y<cr.getListausuarios().length;y++){
            if(matriz[i][3]==txtuser.getText()){
                x=i;
            }
        }
       
}
            }   

        }
         if(existeusuario) {
            existeusuario=true;
        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTE EL USUARIO :C","Error",JOptionPane.WARNING_MESSAGE);
        }
        
            
    }//GEN-LAST:event_btbuscarActionPerformed

    private void btcancelaruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelaruserActionPerformed
        
        this.setVisible(false);// TODO add your handling code here:
        new adminscreen().setVisible(true);
    }//GEN-LAST:event_btcancelaruserActionPerformed

    private void btmodif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodif1ActionPerformed
if(txtpass.getText().equals(txtconfirmpass.getText())){
        int numid = Integer.parseInt(txtid.getText());
        if(!hayespacio(cr.listausuarios))    {
    cr.listausuarios=redimensionar(cr.getListausuarios());
} 
for(int i=0;i<cr.getListausuarios().length;i++){
    if(     cr.getListausuarios()[i]==null){
    cr.listausuarios[cr.getListausuarios().length-2]= new Usuarios(numid,txtnom.getText(),txtape.getText(),txtuser.getText(),txtrol.getText(),txtpass.getText());
    
    break;
            }
}
   
        
 txtid.setText(null);
txtnom.setText(null);
txtape.setText(null);
txtrol.setText(null);
txtpass.setText(null);
txtconfirmpass.setText(null);
txtuser.setText(null); 
}// TODO add your handling code here:
 else{
            JOptionPane.showMessageDialog(null, "lAS CONTRASEÑAS NO COINCIDEN");
            txtconfirmpass.setText(null);
txtpass.setText(null);
        }
    }//GEN-LAST:event_btmodif1ActionPerformed
private Usuarios[] redimensionar(Usuarios[] arreglo) {
    Usuarios[]temporal=new Usuarios[arreglo.length+1];
    for(int i=0; i<arreglo.length;i++){
        temporal[i]=arreglo[i];
    }
        return temporal;
}
    private Boolean hayespacio(Usuarios[] arreglo){
        Boolean espacio =false;
        for(int i=0;i<arreglo.length;i++){
            if(arreglo[i]==null){
                espacio=true;
                break;
            }
        }
        return espacio;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btbuscar;
    private java.awt.Button btcancelaruser;
    private java.awt.Button btmodif1;
    private javax.swing.JPanel jPanel1;
    public java.awt.Label lbape;
    public java.awt.Label lbcontra;
    public java.awt.Label lbcontracon;
    public java.awt.Label lbid;
    public java.awt.Label lbnom;
    public java.awt.Label lbrol;
    public java.awt.Label lbuser;
    public static javax.swing.JTextField txtape;
    private javax.swing.JPasswordField txtconfirmpass;
    public static javax.swing.JTextField txtid;
    public static javax.swing.JTextField txtnom;
    private javax.swing.JPasswordField txtpass;
    public static javax.swing.JTextField txtrol;
    public static javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
