/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bib;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;

/**
 *
 * @author Mariano Rack
 */
public class UserNormal extends javax.swing.JFrame {
 static LbPrestados[]lb= new LbPrestados[2];
    crearuser cr =new crearuser();
log b = new log();
private String us;
int x;
private LbPrestados[] redimensionar1(LbPrestados[] arreglo) {
    LbPrestados[]temporal1=new LbPrestados[arreglo.length+1];
    for(int i=0; i<arreglo.length;i++){
        temporal1[i]=arreglo[i];
    }
        return temporal1;
}
    private Boolean hayespacio1(LbPrestados[] arreglo){
        Boolean espacio =false;
        for(int i=0;i<=arreglo.length;i++){
            if(arreglo[i]==null){
                espacio=true;
                break;
            }
        }
        return espacio;
    }
    public void setUs(String us) {
        this.us = us;
    }

    public String getUs() {
        return us;
    }
    /**
     * Creates new form UserNormal
     */
    public UserNormal (String Us) {
        initComponents();
      lbuser.setText(Us);
 
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbuser = new java.awt.Label();
        label2 = new java.awt.Label();
        btprestamo = new java.awt.Button();
        btlogout = new java.awt.Button();
        btbiblio2 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        txtus1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bib/logousac1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bib/us.png"))); // NOI18N

        lbuser.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        label2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        label2.setText("Usuario: ");

        btprestamo.setActionCommand("Cargar");
        btprestamo.setBackground(new java.awt.Color(0, 102, 51));
        btprestamo.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btprestamo.setForeground(new java.awt.Color(255, 255, 255));
        btprestamo.setLabel("Préstamo de Libro");
        btprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprestamoActionPerformed(evt);
            }
        });

        btlogout.setActionCommand("Cargar");
        btlogout.setBackground(new java.awt.Color(0, 102, 51));
        btlogout.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btlogout.setForeground(new java.awt.Color(255, 255, 255));
        btlogout.setLabel("LOGOUT");
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });

        btbiblio2.setActionCommand("Cargar");
        btbiblio2.setBackground(new java.awt.Color(0, 102, 51));
        btbiblio2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btbiblio2.setForeground(new java.awt.Color(255, 255, 255));
        btbiblio2.setLabel("Biblioteca Virtual");
        btbiblio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbiblio2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jButton1.setText("REPORTE LIBROS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btbiblio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(btlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(lbuser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(txtus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(398, 398, 398)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(205, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38)
                .addComponent(btbiblio2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btprestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btlogout, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(425, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprestamoActionPerformed
      
   new Libros().setVisible(true);
this.setVisible(false); 
 String User = txtus1.getText();
        Libros.txtus2.setText(User);
        // TODO add your handling code here:
    }//GEN-LAST:event_btprestamoActionPerformed

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
    if (!hayespacio1(lb)) {
            lb= redimensionar1(getLb());
        }
            for(int i=0;i<getLb().length;i++){
                
if (getLb()[i] == null){

                    
                    
for(int k=0;k<=BiblioVirtual.getListcarrito().length-1;k++){
    if (BiblioVirtual.getListcarrito()[k] == null) {
}
    else{                    lb[i]= new LbPrestados(BiblioVirtual.getListcarrito()[k].getUser(),BiblioVirtual.getListcarrito()[k].getTitulo(),BiblioVirtual.getListcarrito()[k].getAutor(),BiblioVirtual.getListcarrito()[k].getTipo());
               
    //aqui va
          for(int y=0;y<=lb.length-1;y++)
        {
            if (getLb()[y] != null) {
                System.out.println("----------------");
            System.out.println(lb[y].getUser());
            System.out.println(lb[y].getTitulo());
            System.out.println(lb[y].getAutor());
            System.out.println(lb[y].getTipo());
             System.out.println("----------------");
            
            }
            break;
        }      
              
}
}
            }
else if (getLb()[i] != null){

                    lb=redimensionar1(getLb());
                

for(int k=0;k<BiblioVirtual.getListcarrito().length;k++){
    if (BiblioVirtual.getListcarrito()[k] != null) {
         lb[i]= new LbPrestados(BiblioVirtual.getListcarrito()[k].getUser(),BiblioVirtual.getListcarrito()[k].getTitulo(),BiblioVirtual.getListcarrito()[k].getAutor(),BiblioVirtual.getListcarrito()[k].getTipo());
}
                    //lb[i]= new LbPrestados(lbuser.getText(),BiblioVirtual.getListcarrito()[k].getTitulo(),BiblioVirtual.getListcarrito()[k].getAutor(),BiblioVirtual.getListcarrito()[k].getTipo());
               
    for(int y=0;y<=lb.length-1;y++)
        {
            if (getLb()[y] != null) {
                System.out.println("----------------");
            System.out.println(lb[y].getUser());
            System.out.println(lb[y].getTitulo());
            System.out.println(lb[y].getAutor());
            System.out.println(lb[y].getTipo());
             System.out.println("----------------");
             
            }
        }
               
              
}
            }
break; 
            }
        for(int i=0;i<BiblioVirtual.getListcarrito().length;i++){
        BiblioVirtual.getListcarrito()[i] = null;
    }
             
         new log().setVisible(true);
this.setVisible(false);     
// TODO add your handling code here:
    }//GEN-LAST:event_btlogoutActionPerformed

    private void btbiblio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbiblio2ActionPerformed
this.setVisible(false);
        new BiblioVirtual().setVisible(true); 
        String User = txtus1.getText();
        BiblioVirtual.txtus.setText(User); // TODO add your handling code here:
    }//GEN-LAST:event_btbiblio2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String cadenaHTML = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte</title>\n"
                + "</head>\n"
                + "<body bgcolor=\"#A9D0F5\">\n"
        +"<p><font face=\"Kristen ITC\"><H1 align=\"center\" style=\"color:#04B404;font-size: 40px;\"> Libros en Existencia </H1></p>\n"
                + "<table border = \"2\" CELLPADDING = 15 align = \"center\">\n"
                + "        <tr>"
                + "          <th>Identificador</th>\n"
                + "          <th>Título</th>\n"
         + "          <th>Autor</th>\n"
         + "          <th>Tipo</th>\n"
        + "          <th>Copias</th>\n"
                + "        </tr>";

        for (int i = 0; i <= Individual.getListabiblios().length-3; i++) {
            
                cadenaHTML += "<tr>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getIsbn()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getTitulo()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getAutor()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getTipo()+ "</td>";
                cadenaHTML += "  <td>" + Individual.getListabiblios()[i].getCopias()+ "</td>";
                cadenaHTML += "</tr>";
            
        }

        cadenaHTML += "      </table>\n"
                + "</body>\n"
                + "</html>";

        File archivo = new File("LibrosExistencia.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
            bw.write(cadenaHTML);
            bw.close();
        } catch (Exception e) {
        }          // TOD your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserNormal("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btbiblio2;
    private java.awt.Button btlogout;
    private java.awt.Button btprestamo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label2;
    public static java.awt.Label lbuser;
    public static javax.swing.JTextField txtus1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lb
     */
    public static LbPrestados[] getLb() {
        return lb;
    }
}
