/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bib;

import static Bib.BiblioVirtual.tbmo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mariano Rack
 */
public class Ver extends javax.swing.JFrame {
int n,x;
    /**
     * Creates new form Ver
     */
    public Ver() {
        initComponents();
         String[][] matriz = new String[BiblioVirtual.getListcarrito().length][14];
        for (int i = 0; i < BiblioVirtual.getListcarrito().length; i++) {
             n=n+1;
            if (BiblioVirtual.getListcarrito()[i] != null) {
                if(Individual.getListabiblios()[i].getTipo()=="Libro digital"){
                matriz[i][0]=""+n;
                 matriz[i][1]=""+BiblioVirtual.getListcarrito()[i].getAutor();
        matriz[i][2]=BiblioVirtual.getListcarrito()[i].getAño();
        matriz[i][3]=BiblioVirtual.getListcarrito()[i].getTitulo();
        matriz[i][4]=BiblioVirtual.getListcarrito()[i].getDescripcion();
        matriz[i][5]=BiblioVirtual.getListcarrito()[i].getPalabras();
        matriz[i][6]=BiblioVirtual.getListcarrito()[i].getEdicion();
        matriz[i][7]=BiblioVirtual.getListcarrito()[i].getTemas();
        matriz[i][8]=""+BiblioVirtual.getListcarrito()[i].getCopias();
        matriz[i][9]=BiblioVirtual.getListcarrito()[i].getArea();
        matriz[i][10]=BiblioVirtual.getListcarrito()[i].getCategoria();
        matriz[i][11]=""+BiblioVirtual.getListcarrito()[i].getIsbn();
        matriz[i][12]=BiblioVirtual.getListcarrito()[i].getTipo();
        matriz[i][13]=BiblioVirtual.getListcarrito()[i].getIsbnreal();
                
            }
            }
           
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN"};
        tb.setModel(new DefaultTableModel(
                matriz,
                encabezado
        )); 
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lbid = new javax.swing.JLabel();
        btregresar2 = new java.awt.Button();
        lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        tb.setBackground(new java.awt.Color(153, 204, 255));
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbid.setForeground(new java.awt.Color(0, 0, 0));

        btregresar2.setActionCommand("Cargar");
        btregresar2.setBackground(new java.awt.Color(0, 102, 51));
        btregresar2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btregresar2.setForeground(new java.awt.Color(255, 255, 255));
        btregresar2.setLabel("Regresar");
        btregresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregresar2ActionPerformed(evt);
            }
        });

        lb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btregresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb)
                                .addGap(123, 123, 123)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbid))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btregresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbid)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
int fila = this.tb.getSelectedRow();
// TODO add your handling code here:

                 for(int i=0;i<=BiblioVirtual.getListcarrito().length;i++){
                
if (BiblioVirtual.getListcarrito()[i] == null){
    String n=""+BiblioVirtual.getListcarrito()[fila].getIsbn();
    lb.setText(n);
lbid.setText("Libro: "+BiblioVirtual.getListcarrito()[fila].getTitulo()+" "+"Autor: "+BiblioVirtual.getListcarrito()[fila].getAutor());
x=i;
                break;

            }
            }          // TODO add your handling code here:
    }//GEN-LAST:event_tbMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
for(int i=0;i<BiblioVirtual.getListcarrito().length;i++){
            if(     BiblioVirtual.getListcarrito()[i]!=null){
                
                         int is = Integer.parseInt(lb.getText());
                 if(BiblioVirtual.getListcarrito()[i].getIsbn()==is)    {
                 
                                     BiblioVirtual.getListcarrito()[i] = null;
                     
                 }
                break;
            }
        }    
String[][] matriz = new String[BiblioVirtual.getListcarrito().length][14];
        for (int i = 0; i < BiblioVirtual.getListcarrito().length; i++) {
             n=n+1;
            if (BiblioVirtual.getListcarrito()[i] != null) {
                matriz[i][0]=""+n;
                 matriz[i][1]=""+BiblioVirtual.getListcarrito()[i].getAutor();
        matriz[i][2]=BiblioVirtual.getListcarrito()[i].getAño();
        matriz[i][3]=BiblioVirtual.getListcarrito()[i].getTitulo();
        matriz[i][4]=BiblioVirtual.getListcarrito()[i].getDescripcion();
        matriz[i][5]=BiblioVirtual.getListcarrito()[i].getPalabras();
        matriz[i][6]=BiblioVirtual.getListcarrito()[i].getEdicion();
        matriz[i][7]=BiblioVirtual.getListcarrito()[i].getTemas();
        matriz[i][8]=""+BiblioVirtual.getListcarrito()[i].getCopias();
        matriz[i][9]=BiblioVirtual.getListcarrito()[i].getArea();
        matriz[i][10]=BiblioVirtual.getListcarrito()[i].getCategoria();
        matriz[i][11]=""+BiblioVirtual.getListcarrito()[i].getIsbn();
        matriz[i][12]=BiblioVirtual.getListcarrito()[i].getTipo();
        matriz[i][13]=BiblioVirtual.getListcarrito()[i].getIsbnreal();
                
            }
           
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN"};
        tb.setModel(new DefaultTableModel(
                matriz,
                encabezado
        ));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btregresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregresar2ActionPerformed
  this.setVisible(false);
        new BiblioVirtual().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_btregresar2ActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
       String[][] matriz = new String[BiblioVirtual.getListcarrito().length][14];
        for (int i = 0; i < BiblioVirtual.getListcarrito().length; i++) {
             n=n+1;
            if (BiblioVirtual.getListcarrito()[i] != null) {
                matriz[i][0]=""+n;
                 matriz[i][1]=""+BiblioVirtual.getListcarrito()[i].getAutor();
        matriz[i][2]=BiblioVirtual.getListcarrito()[i].getAño();
        matriz[i][3]=BiblioVirtual.getListcarrito()[i].getTitulo();
        matriz[i][4]=BiblioVirtual.getListcarrito()[i].getDescripcion();
        matriz[i][5]=BiblioVirtual.getListcarrito()[i].getPalabras();
        matriz[i][6]=BiblioVirtual.getListcarrito()[i].getEdicion();
        matriz[i][7]=BiblioVirtual.getListcarrito()[i].getTemas();
        matriz[i][8]=""+BiblioVirtual.getListcarrito()[i].getCopias();
        matriz[i][9]=BiblioVirtual.getListcarrito()[i].getArea();
        matriz[i][10]=BiblioVirtual.getListcarrito()[i].getCategoria();
        matriz[i][11]=""+BiblioVirtual.getListcarrito()[i].getIsbn();
        matriz[i][12]=BiblioVirtual.getListcarrito()[i].getTipo();
        matriz[i][13]=BiblioVirtual.getListcarrito()[i].getIsbnreal();
                
            }
           
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN"};
        tb.setModel(new DefaultTableModel(
                matriz,
                encabezado
        ));   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btregresar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbid;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
