/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bib;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mariano Rack
 */
public class VerPrestamos extends javax.swing.JFrame {
int n;
Individual cr = new Individual();
    /**
     * Creates new form VerPrestamos
     */
    public VerPrestamos() {
        initComponents();
        
          String[][] matriz = new String[BiblioVirtual.getListcarrito().length][15];
        for (int i = 0; i < BiblioVirtual.getListcarrito().length; i++) {
             n=n+1;
            if (BiblioVirtual.getListcarrito()[i] != null) {
                if(BiblioVirtual.getListcarrito()[i].getTipo()!="Libro digital"){
                matriz[i][0]=""+n;
                 matriz[i][1]=""+BiblioVirtual.getListcarrito()[i].getAutor();
        matriz[i][2]=BiblioVirtual.getListcarrito()[i].getAño();
        matriz[i][3]=BiblioVirtual.getListcarrito()[i].getTitulo();
        matriz[i][4]=BiblioVirtual.getListcarrito()[i].getDescripcion();
        matriz[i][5]=BiblioVirtual.getListcarrito()[i].getPalabras();
        matriz[i][6]=BiblioVirtual.getListcarrito()[i].getEdicion();
        matriz[i][7]=BiblioVirtual.getListcarrito()[i].getTemas();
        matriz[i][8]=""+(BiblioVirtual.getListcarrito()[i].getCopias());
        matriz[i][9]=BiblioVirtual.getListcarrito()[i].getArea();
        matriz[i][10]=BiblioVirtual.getListcarrito()[i].getCategoria();
        matriz[i][11]=""+BiblioVirtual.getListcarrito()[i].getIsbn();
        matriz[i][12]=BiblioVirtual.getListcarrito()[i].getTipo();
        matriz[i][13]=BiblioVirtual.getListcarrito()[i].getIsbnreal();
              matriz[i][14]=""+(BiblioVirtual.getListcarrito()[i].getCopias());   
              for(int j=0; j<=Individual.getListabiblios().length;j++ ){
                  if(Individual.getListabiblios()[j] != null){
              if(Individual.getListabiblios()[j].getIsbn()==BiblioVirtual.getListcarrito()[i].getIsbn())    {
                   String ej=""+BiblioVirtual.getListcarrito()[i].getCopias();
    Individual.listabiblios[i]= new Biblios(BiblioVirtual.getListcarrito()[i].getAutor(),BiblioVirtual.getListcarrito()[i].getAño(),BiblioVirtual.getListcarrito()[i].getTitulo(),BiblioVirtual.getListcarrito()[i].getDescripcion(),BiblioVirtual.getListcarrito()[i].getPalabras(),BiblioVirtual.getListcarrito()[i].getEdicion(),BiblioVirtual.getListcarrito()[i].getTemas(),BiblioVirtual.getListcarrito()[i].getCopias()-1,BiblioVirtual.getListcarrito()[i].getArea(),BiblioVirtual.getListcarrito()[i].getCategoria(),BiblioVirtual.getListcarrito()[i].getIsbn(),BiblioVirtual.getListcarrito()[i].getTipo(),BiblioVirtual.getListcarrito()[i].getIsbnreal(),ej);
              }
    break;
            
              }
              }
              if(BiblioVirtual.getListcarrito()[i].getCopias()-1<0){
                  JOptionPane.showMessageDialog(null, "Ya no se encuentran unidades disponibles del libro: "+BiblioVirtual.getListcarrito()[i].getTitulo());
              }
            }
            }
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN","Disponibles"};
        tb.setModel(new DefaultTableModel(
                matriz,
                encabezado
        )); 
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        btlogout2 = new java.awt.Button();
        btregresar2 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        label2.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        label2.setText("Listado de Préstamos");

        btlogout2.setActionCommand("Cargar");
        btlogout2.setBackground(new java.awt.Color(0, 102, 51));
        btlogout2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btlogout2.setForeground(new java.awt.Color(255, 255, 255));
        btlogout2.setLabel("Logout");
        btlogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogout2ActionPerformed(evt);
            }
        });

        btregresar2.setActionCommand("Cargar");
        btregresar2.setBackground(new java.awt.Color(0, 102, 51));
        btregresar2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 14)); // NOI18N
        btregresar2.setForeground(new java.awt.Color(255, 255, 255));
        btregresar2.setLabel("Regresar");
        btregresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregresar2ActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Titulo", "Tipo", "Devolver"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        tb.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tbComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btregresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btlogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btlogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btregresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogout2ActionPerformed
         if (!hayespacio1(UserNormal.lb)) {
            UserNormal.lb= redimensionar1(UserNormal.getLb());
        }
            for(int i=0;i<=UserNormal.getLb().length;i++){
                
if (UserNormal.getLb()[i] == null){

                    UserNormal.lb=redimensionar1(UserNormal.getLb());
                    
                    
for(int k=0;k<=BiblioVirtual.getListcarrito().length;k++){
    if (BiblioVirtual.getListcarrito()[i] != null) {
}
                    UserNormal.lb[i]= new LbPrestados("",BiblioVirtual.getListcarrito()[k].getTitulo(),BiblioVirtual.getListcarrito()[k].getAutor(),BiblioVirtual.getListcarrito()[k].getTipo());
                
    for(int y=1;y<UserNormal.lb.length;y++)
        {
            if (UserNormal.getLb()[y] != null) {
                System.out.println("----------------");
            System.out.println(UserNormal.lb[y].getUser());
            System.out.println(UserNormal.lb[y].getTitulo());
            System.out.println(UserNormal.lb[y].getAutor());
            System.out.println(UserNormal.lb[y].getTipo());
             System.out.println("----------------");
            break; 
            }
        }
                break;
              
}
            }
if (UserNormal.getLb()[i] != null){

                    UserNormal.lb=redimensionar1(UserNormal.getLb());
                    String concat="";
                    
for(int k=0;k<=BiblioVirtual.getListcarrito().length;k++){
    if (BiblioVirtual.getListcarrito()[i] != null) {
}
                    UserNormal.lb[i]= new LbPrestados("",BiblioVirtual.getListcarrito()[k].getTitulo(),BiblioVirtual.getListcarrito()[k].getAutor(),BiblioVirtual.getListcarrito()[k].getTipo());
                
    for(int y=0;y<UserNormal.lb.length;y++)
        {
            if (UserNormal.getLb()[y] != null) {
                System.out.println("----------------");
            System.out.println(UserNormal.lb[y].getUser());
            System.out.println(UserNormal.lb[y].getTitulo());
            System.out.println(UserNormal.lb[y].getAutor());
            System.out.println(UserNormal.lb[y].getTipo());
             System.out.println("----------------");
            break; 
            }
        }
                break;
              
}
            }
break; 
            }
        for(int i=0;i<BiblioVirtual.getListcarrito().length;i++){
        BiblioVirtual.getListcarrito()[i] = null;
    }
            
         new log().setVisible(true);
this.setVisible(false);      
    }//GEN-LAST:event_btlogout2ActionPerformed
private LbPrestados[] redimensionar1(LbPrestados[] arreglo) {
    LbPrestados[]temporal1=new LbPrestados[arreglo.length+1];
    for(int i=0; i<arreglo.length;i++){
        temporal1[i]=arreglo[i];
    }
        return temporal1;
}
    private Boolean hayespacio1(LbPrestados[] arreglo){
        Boolean espacio =false;
        for(int i=0;i<=arreglo.length;i++){
            if(arreglo[i]==null){
                espacio=true;
                break;
            }
        }
        return espacio;
    }
    private void btregresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregresar2ActionPerformed
this.setVisible(false);
        new  BiblioVirtual().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btregresar2ActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        int fila = this.tb.getSelectedRow();
            for (int i = 0; i < BiblioVirtual.getListcarrito().length; i++) {
             n=n+1;
            if (BiblioVirtual.getListcarrito()[i] != null) { 
              for(int j=0; j<=Individual.getListabiblios().length;j++ ){
                  if(Individual.getListabiblios()[j] != null){
              if(Individual.getListabiblios()[j].getIsbn()==BiblioVirtual.getListcarrito()[fila].getIsbn())    {
                  String ej=""+BiblioVirtual.getListcarrito()[i].getCopias();
              Individual.listabiblios[i]= new Biblios(BiblioVirtual.getListcarrito()[i].getAutor(),BiblioVirtual.getListcarrito()[i].getAño(),BiblioVirtual.getListcarrito()[i].getTitulo(),BiblioVirtual.getListcarrito()[i].getDescripcion(),BiblioVirtual.getListcarrito()[i].getPalabras(),BiblioVirtual.getListcarrito()[i].getEdicion(),BiblioVirtual.getListcarrito()[i].getTemas(),BiblioVirtual.getListcarrito()[i].getCopias()+1,BiblioVirtual.getListcarrito()[i].getArea(),BiblioVirtual.getListcarrito()[i].getCategoria(),BiblioVirtual.getListcarrito()[i].getIsbn(),BiblioVirtual.getListcarrito()[i].getTipo(),BiblioVirtual.getListcarrito()[i].getIsbnreal(),ej);
              }
    break;
            
              }
              }
             
            
            }
        }
 // TODO add your handling code here:
    }//GEN-LAST:event_tbMouseClicked

    private void tbComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tbComponentShown
  String[][] matriz = new String[BiblioVirtual.getListcarrito().length][15];
        for (int i = 0; i < BiblioVirtual.getListcarrito().length; i++) {
             n=n+1;
            if (BiblioVirtual.getListcarrito()[i] != null) {
                if(BiblioVirtual.getListcarrito()[i].getTipo()!="Libro digital"){
                matriz[i][0]=""+n;
                 matriz[i][1]=""+BiblioVirtual.getListcarrito()[i].getAutor();
        matriz[i][2]=BiblioVirtual.getListcarrito()[i].getAño();
        matriz[i][3]=BiblioVirtual.getListcarrito()[i].getTitulo();
        matriz[i][4]=BiblioVirtual.getListcarrito()[i].getDescripcion();
        matriz[i][5]=BiblioVirtual.getListcarrito()[i].getPalabras();
        matriz[i][6]=BiblioVirtual.getListcarrito()[i].getEdicion();
        matriz[i][7]=BiblioVirtual.getListcarrito()[i].getTemas();
        matriz[i][8]=""+(BiblioVirtual.getListcarrito()[i].getCopias());
        matriz[i][9]=BiblioVirtual.getListcarrito()[i].getArea();
        matriz[i][10]=BiblioVirtual.getListcarrito()[i].getCategoria();
        matriz[i][11]=""+BiblioVirtual.getListcarrito()[i].getIsbn();
        matriz[i][12]=BiblioVirtual.getListcarrito()[i].getTipo();
        matriz[i][13]=BiblioVirtual.getListcarrito()[i].getIsbnreal();
              matriz[i][14]=""+(BiblioVirtual.getListcarrito()[i].getCopias());   
              for(int j=0; j<=Individual.getListabiblios().length;j++ ){
                  if(Individual.getListabiblios()[j] != null){
              if(Individual.getListabiblios()[j].getIsbn()==BiblioVirtual.getListcarrito()[i].getIsbn())    {
                   String ej=""+BiblioVirtual.getListcarrito()[i].getCopias();
    Individual.listabiblios[i]= new Biblios(BiblioVirtual.getListcarrito()[i].getAutor(),BiblioVirtual.getListcarrito()[i].getAño(),BiblioVirtual.getListcarrito()[i].getTitulo(),BiblioVirtual.getListcarrito()[i].getDescripcion(),BiblioVirtual.getListcarrito()[i].getPalabras(),BiblioVirtual.getListcarrito()[i].getEdicion(),BiblioVirtual.getListcarrito()[i].getTemas(),BiblioVirtual.getListcarrito()[i].getCopias()-1,BiblioVirtual.getListcarrito()[i].getArea(),BiblioVirtual.getListcarrito()[i].getCategoria(),BiblioVirtual.getListcarrito()[i].getIsbn(),BiblioVirtual.getListcarrito()[i].getTipo(),BiblioVirtual.getListcarrito()[i].getIsbnreal(),ej);
              }
    break;
            
              }
              }
              if(BiblioVirtual.getListcarrito()[i].getCopias()-1<0){
                  JOptionPane.showMessageDialog(null, "Ya no se encuentran unidades disponibles del libro: "+BiblioVirtual.getListcarrito()[i].getTitulo());
              }
            }
            }
        }
 
   String[] encabezado = {"No", "Autor","Año","Titulo","Descripción","Palabras","Edición", "Temas", "Copias", "Área", "Categoría", "ID", "Tipo", "ISBN","Disponibles"};
        tb.setModel(new DefaultTableModel(
                matriz,
                encabezado
        ));         // TODO add your handling code here:
    }//GEN-LAST:event_tbComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btlogout2;
    private java.awt.Button btregresar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label2;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
